name: Deploy (Development)

on:
  push:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn
      - id: npmver
        name: NPM SemVer
        uses: odinr/action-npm-semver@v1
        with:
          version: current
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        if: steps.npmver.outputs.prerelease == 'nightly'
        with:
          access: public
          check-version: true
          token: ${{ secrets.NPM_TOKEN }}
          tag: nightly
