name: Deploy (Production)

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.15
      - name: Use pnpm storage cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store/v3
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          check-version: true
          token: ${{ secrets.NPM_TOKEN }}